'546
'' 
' This code was generated by a tool. Any changes made manually will be lost
' the next time this code is regenerated.
'' 
Imports System.Reflection

<Assembly: AssemblyVersion("2.19.546.0116")> 
<Assembly: AssemblyFileVersion("2.19.546.0116")> 
<Assembly: AssemblyCopyright("Copyright © 2017 - 2018")>

