//20
// 
// This code was generated by a tool. Any changes made manually will be lost
//the next time this code is regenerated.
// 
using System.Reflection;

[assembly: AssemblyVersion("1.0.020.0117")]
[assembly: AssemblyFileVersion("1.0.020.0117")]
[assembly: AssemblyCopyright("Copyright 2004-2013 Victor Boctor - Futureware, Copyright © 2014 - 2018 - Starship Avalon Projects")]



