*MSPK V07.00 Silver Monkey
*MonkeySpeak Script File
*Created by Gerolkae   

(0:34) When the bot enters a Dream,
		(5:102) print {Beginning Turret Tests} to the log.
		(5:102) print {Arrived in Dream %DREAMNAME} to the log.

(0:34) When the bot enters a Dream,
    (1:35) and the Dream Name is not {The Shoddy Ribbon},
    (1:35) and the Dream Name is not {Furrabian Nights},
	   (5:16) whisper {DREAMNAME is Not %DREAMNAME} to furre named {%BOTCONTROLLER}.
		(5:102) print {NOT MY MINTY~~~} to the log.
         (5:16) whisper {Downloading Dream furc://theshoddyribbon} to furre named {%BOTCONTROLLER}.
	  (5:10) say {`fdl furc://theshoddyribbon}.


*Endtriggers* 8888 *Endtriggers*
