//0
// 
// This code was generated by a tool. Any changes made manually will be lost
//the next time this code is regenerated.
// 
using System.Reflection;

[assembly: AssemblyInformationalVersion("1.0.PreAlpha 0")]

