//3
// 
// This code was generated by a tool. Any changes made manually will be lost
//the next time this code is regenerated.
// 
using System.Reflection;

[assembly: AssemblyVersion("1.1.003.0908")]
[assembly: AssemblyFileVersion("1.1.003.0908")]
[assembly: AssemblyCopyright("Copyright ©  2012 - 2017")]

