



//428
// 
// This code was generated by a tool. Any changes made manually will be lost
//the next time this code is regenerated.
// 
using System.Reflection;

[assembly: AssemblyVersion("7.0.428.0114")]
[assembly: AssemblyFileVersion("7.0.428.0114")]
[assembly: AssemblyCopyright("Copyright © 2012 - 2018")]



