//12
// 
// This code was generated by a tool. Any changes made manually will be lost
//the next time this code is regenerated.
// 
using System.Reflection;

[assembly: AssemblyVersion("3.0.012.0110")]
[assembly: AssemblyFileVersion("3.0.012.0110")]
[assembly: AssemblyCopyright("Copyright � 2012 - 2018")]



