'16
'' 
' This code was generated by a tool. Any changes made manually will be lost
' the next time this code is regenerated.
'' 
Imports System.Reflection

<Assembly: AssemblyVersion("1.1.016.0704")> 
<Assembly: AssemblyFileVersion("1.1.016.0704")> 
<Assembly: AssemblyCopyright("Copyright © 2017 - 2017")>
