'399
'' 
' This code was generated by a tool. Any changes made manually will be lost
' the next time this code is regenerated.
'' 
Imports System.Reflection

<Assembly: AssemblyVersion("2.18.399.0903")> 
<Assembly: AssemblyFileVersion("2.18.399.0903")> 
