'340
'' 
' This code was generated by a tool. Any changes made manually will be lost
' the next time this code is regenerated.
'' 
Imports System.Reflection

<Assembly: AssemblyVersion("2.17.340.0531")> 
<Assembly: AssemblyFileVersion("2.17.340.0531")> 
