//63
// 
// This code was generated by a tool. Any changes made manually will be lost
//the next time this code is regenerated.
// 
using System.Reflection;

[assembly: AssemblyVersion("3.0.063.0403")]
[assembly: AssemblyFileVersion("3.0.063.0403")]
[assembly: AssemblyCopyright("Copyright © 2012 - 2018")]



