



'22
'' 
' This code was generated by a tool. Any changes made manually will be lost
' the next time this code is regenerated.
'' 
Imports System.Reflection


<Assembly: AssemblyInformationalVersion("2.19.PreAlpha 22")>
