//21
// 
// This code was generated by a tool. Any changes made manually will be lost
//the next time this code is regenerated.
// 
using System.Reflection;

[assembly: AssemblyVersion("1.0.021.0317")]
[assembly: AssemblyFileVersion("1.0.021.0317")]
[assembly: AssemblyCopyright("Copyright © 2012 - 2018")]



