//14
// 
// This code was generated by a tool. Any changes made manually will be lost
//the next time this code is regenerated.
// 
using System.Reflection;

[assembly: AssemblyVersion("1.1.014.0928")]
[assembly: AssemblyFileVersion("1.1.014.0928")]
[assembly: AssemblyCopyright("Copyright 2016 - 2017 StarshipAvalonProjects")]

