'274
'' 
' This code was generated by a tool. Any changes made manually will be lost
' the next time this code is regenerated.
'' 
Imports System.Reflection

<Assembly: AssemblyVersion("1.1.274.0910")> 
<Assembly: AssemblyFileVersion("1.1.274.0910")> 
<Assembly: AssemblyCopyright("Copyright © 2012 - 2017")>

