'65
'' 
' This code was generated by a tool. Any changes made manually will be lost
' the next time this code is regenerated.
'' 
Imports System.Reflection

<Assembly: AssemblyVersion("1.0.065.0122")> 
<Assembly: AssemblyFileVersion("1.0.065.0122")> 
