'26
'' 
' This code was generated by a tool. Any changes made manually will be lost
' the next time this code is regenerated.
'' 
Imports System.Reflection

<Assembly: AssemblyVersion("1.1.026.0413")> 
<Assembly: AssemblyFileVersion("1.1.026.0413")> 
