*MSPK V04.00 Silver Monkey
*MonkeySpeak Script File
*Created by <Pardryll> 

(0:0) When the bot starts,
    (5:203) create file {wmd.txt}.


(0:1) When the bot logs into furcadia,
    (5:7) whisper {Bot is online!} to furre named {Gerolkae} even if they're offline.

(0:90) When the bot enters a dream,
 (1:24) and the Dream Name is not {TheShoddyRibbon},
 (1:24) and the Dream Name is not {FurrabianNights},
    (5:0) say {THIS IS NOT MY HOME! YOU'RE NOT MY MINTY!}.

(0:90) When the bot enters a dream,
  (1:19) and the bot is the Dream owner,
    (5:0) say {!botspot}.




(0:16) When someone whispers {crunchatize},
    (5:5) whisper {Crunchatize me, captain!} to the triggering furre.
    (5:6) whisper {Gave share to %NAME} to furre named {Gerolkae}.
    (5:23)  give share to the furre named {%NAME} if they're in the Dream right now.


(0:16) When someone whispers {roll out},
     (5:5) whisper {Transform and roll out!} to the triggering furre.
     (5:6) whisper {Removed share from %NAME} to furre named {Gerolkae}.
     (5:22) remove share from the furre named {%NAME} if they're in the Dream right now.


*Endtriggers* 8888 *Endtriggers*
